//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban.Desktop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<KanbanConfiguration xmlns:xsi=\"http://w" +
            "ww.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">" +
            "\r\n  <ProjectId>12</ProjectId>\r\n  <HorizontalDimension>\r\n    <DimensionName>Statu" +
            "s.Name</DimensionName>\r\n    <SortingPath>Status.Id</SortingPath>\r\n  </Horizontal" +
            "Dimension>\r\n  <VerticalDimension>\r\n    <DimensionName>AssignedTo.Name</Dimension" +
            "Name>\r\n  </VerticalDimension>\r\n  <CardItemsConfiguration>\r\n    <CardsItems>\r\n   " +
            "     <CardItem>\r\n          <Area>Main</Area>\r\n          <Path>Subject</Path>\r\n  " +
            "      </CardItem>\r\n        <CardItem>\r\n          <Area>Short</Area>\r\n          <" +
            "Path>Tracker</Path>\r\n        </CardItem>\r\n        <CardItem>\r\n          <Area>Sh" +
            "ort</Area>\r\n          <Path>Priority</Path>\r\n        </CardItem>\r\n        <CardI" +
            "tem>\r\n          <Area>\r\n        </Area>\r\n          <Path>Description</Path>\r\n   " +
            "     </CardItem>\r\n    </CardsItems>\r\n    <ColorSettings>\r\n      <Path>Priority.N" +
            "ame</Path>\r\n      <ColorMaps>\r\n        <ColorMap>\r\n          <Value>Низкий</Valu" +
            "e>\r\n          <CardColors>\r\n            <BorderColor>#7DBB00</BorderColor>\r\n    " +
            "        <BackgroundColor>#DCFFC2</BackgroundColor>\r\n          </CardColors>\r\n   " +
            "     </ColorMap>\r\n        <ColorMap>\r\n          <Value>Нормальный</Value>\r\n     " +
            "     <CardColors>\r\n            <BorderColor>#FFB13B</BorderColor>\r\n            <" +
            "BackgroundColor>#FFE7B6</BackgroundColor>\r\n          </CardColors>\r\n        </Co" +
            "lorMap>\r\n        <ColorMap>\r\n          <Value>Высокий</Value>\r\n          <CardCo" +
            "lors>\r\n            <BorderColor>#FF8099</BorderColor>\r\n            <BackgroundCo" +
            "lor>#FFCCD6</BackgroundColor>\r\n          </CardColors>\r\n        </ColorMap>\r\n   " +
            "     <ColorMap>\r\n          <Value>low</Value>\r\n          <CardColors>\r\n         " +
            "   <BorderColor>#7DBB00</BorderColor>\r\n            <BackgroundColor>#DCFFC2</Bac" +
            "kgroundColor>\r\n          </CardColors>\r\n        </ColorMap>\r\n        <ColorMap>\r" +
            "\n          <Value>normal</Value>\r\n          <CardColors>\r\n            <BorderCol" +
            "or>#FFB13B</BorderColor>\r\n            <BackgroundColor>#FFE7B6</BackgroundColor>" +
            "\r\n          </CardColors>\r\n        </ColorMap>\r\n        <ColorMap>\r\n          <V" +
            "alue>high</Value>\r\n          <CardColors>\r\n            <BorderColor>#FF8099</Bor" +
            "derColor>\r\n            <BackgroundColor>#FFCCD6</BackgroundColor>\r\n          </C" +
            "ardColors>\r\n        </ColorMap>\r\n      </ColorMaps>\r\n    </ColorSettings>\r\n  </C" +
            "ardItemsConfiguration>\r\n</KanbanConfiguration>")]
        public string h_status_v_assigned_c_subject_treker_details {
            get {
                return ((string)(this["h_status_v_assigned_c_subject_treker_details"]));
            }
            set {
                this["h_status_v_assigned_c_subject_treker_details"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<KanbanConfiguration xmlns:xsi=\"http://w" +
            "ww.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">" +
            "\r\n  <ProjectId>18</ProjectId>\r\n  <HorizontalDimension>\r\n    <DimensionName>Statu" +
            "s.Name</DimensionName>\r\n    <SortingPath>Status.Id</SortingPath>\r\n    <ValuesFil" +
            "ter>\r\n      <string>Новая</string>\r\n      <string>В процессе</string>\r\n      <st" +
            "ring>Решена</string>\r\n    </ValuesFilter>\r\n  </HorizontalDimension>\r\n  <Vertical" +
            "Dimension>\r\n    <DimensionName>Tracker.Name</DimensionName>\r\n    <ValuesFilter>\r" +
            "\n      <string>Входящий вызов</string>\r\n      <string>Исходящий вызов</string>\r\n" +
            "    </ValuesFilter>    \r\n  </VerticalDimension>\r\n  <CardItemsConfiguration>\r\n   " +
            " <CardsItems>\r\n        <CardItem>\r\n          <Area>Main</Area>\r\n          <Path>" +
            "Subject</Path>\r\n        </CardItem>\r\n    </CardsItems>\r\n    <ColorSettings>\r\n   " +
            "   <Path>Priority.Name</Path>\r\n      <ColorMaps>\r\n        <ColorMap>\r\n          " +
            "<Value>Низкий</Value>\r\n          <CardColors>\r\n            <BorderColor>#7DBB00<" +
            "/BorderColor>\r\n            <BackgroundColor>#DCFFC2</BackgroundColor>\r\n         " +
            " </CardColors>\r\n        </ColorMap>\r\n        <ColorMap>\r\n          <Value>Нормал" +
            "ьный</Value>\r\n          <CardColors>\r\n            <BorderColor>#FFB13B</BorderCo" +
            "lor>\r\n            <BackgroundColor>#FFE7B6</BackgroundColor>\r\n          </CardCo" +
            "lors>\r\n        </ColorMap>\r\n        <ColorMap>\r\n          <Value>Высокий</Value>" +
            "\r\n          <CardColors>\r\n            <BorderColor>#FF8099</BorderColor>\r\n      " +
            "      <BackgroundColor>#FFCCD6</BackgroundColor>\r\n          </CardColors>\r\n     " +
            "   </ColorMap>\r\n        <ColorMap>\r\n          <Value>Срочный</Value>\r\n          " +
            "<CardColors>\r\n            <BorderColor>#C69CF3</BorderColor>\r\n            <Backg" +
            "roundColor>#E2D2F2</BackgroundColor>\r\n          </CardColors>\r\n        </ColorMa" +
            "p>\r\n        <ColorMap>\r\n          <Value>low</Value>\r\n          <CardColors>\r\n  " +
            "          <BorderColor>#7DBB00</BorderColor>\r\n            <BackgroundColor>#DCFF" +
            "C2</BackgroundColor>\r\n          </CardColors>\r\n        </ColorMap>\r\n        <Col" +
            "orMap>\r\n          <Value>normal</Value>\r\n          <CardColors>\r\n            <Bo" +
            "rderColor>#FFB13B</BorderColor>\r\n            <BackgroundColor>#FFE7B6</Backgroun" +
            "dColor>\r\n          </CardColors>\r\n        </ColorMap>\r\n        <ColorMap>\r\n     " +
            "     <Value>high</Value>\r\n          <CardColors>\r\n            <BorderColor>#FF80" +
            "99</BorderColor>\r\n            <BackgroundColor>#FFCCD6</BackgroundColor>\r\n      " +
            "    </CardColors>\r\n        </ColorMap>\r\n      </ColorMaps>\r\n    </ColorSettings>" +
            "\r\n  </CardItemsConfiguration>\r\n</KanbanConfiguration>")]
        public string ods {
            get {
                return ((string)(this["ods"]));
            }
            set {
                this["ods"] = value;
            }
        }
    }
}
